on:
  push:
    branches:
      - main

name: bun workflow
jobs:
  my-job:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun ./src/app.ts
      - run: bun run build
